export const Errors = [
    { code: "errors.missingorganisation", default: "Missing organisation header", status: 400 },
    { code: "errors.missinglanguage", default: "Missing language header", status: 400 },
    { code: "errors.invalidchart", default: "Invalid chart configuration", status: 400 },
    { code: "errors.invalidscenario", default: "Invalid scenario configuration", status: 400 },
    { code: "errors.passwordtooshort", default: "Password too short", status: 400 },
    { code: "errors.passwordtoolong", default: "Password too long", status: 400 },
    { code: "errors.passwordlowercase", default: "Lowercase character required", status: 400 },
    { code: "errors.passworduppercase", default: "Uppercase character required", status: 400 },
    { code: "errors.passwordnumber", default: "Number required", status: 400 },
    { code: "errors.passwordspecial", default: "Special character required", status: 400 },
    { code: "errors.authenticationfailed", default: "Authentication failed", status: 401 },
    { code: "errors.noregistereduser", default: "No registered user", status: 401 },
    { code: "errors.badcredentials", default: "Bad credentials", status: 401 },
    { code: "errors.unauthorizedorganisation", default: "Unauthorized organisation", status: 403 },
    { code: "errors.unauthorizedextension", default: "Unauthorized extension", status: 403 },
    { code: "errors.unauthorizeduser", default: "Unauthorized user", status: 403 },
    { code: "errors.usernotinorganisation", default: "User not in organisation", status: 403 },
    { code: "errors.noadminprivilege", default: "No admin privilege", status: 403 },
    { code: "errors.dashboardLocked", default: "Dashboard locked", status: 403 },
    { code: "errors.entitynotfound", default: "Entity not found", status: 404 },
    { code: "errors.imagenotfound", default: "Image not found", status: 404 },
    { code: "errors.tokennotfound", default: "Token not found", status: 404 },
    { code: "errors.alreadyregistereduser", default: "Already registered user", status: 409 },
    { code: "errors.devicealreadyinorganisation", default: "Device already in organisation", status: 409 },
    { code: "errors.devicealreadywatched", default: "Device already watched", status: 409 },
    { code: "errors.useralreadyinorganisation", default: "User already in organisation", status: 409 },
    { code: "errors.emailfailure", default: "Email failure", status: 422 },
    { code: "errors.requirevalidation", default: "Require validation", status: 422 },
    { code: "errors.databaseerror", default: "Database error", status: 449 },
    { code: "errors.graphsettingserror", default: "Microsoft graph settings error", status: 500 },
    { code: "errors.graphusererror", default: "Microsoft graph user error", status: 500 },
    { code: "errors.nomappableproperty", default: "No mappable property", status: 500 },
    { code: "errors.unvalidextensioncookie", default: "Unvalid extension cookie", status: 500 },
    { code: "errors.unexpectederror", default: "Unexpected error", status: 500 }
  ];